spring:
  profiles:
    active: dev # 기본적으로 dev 환경임을 명시
  thymeleaf:
    cache: false # 타임리프 캐시 끄기
    prefix: file:src/main/resources/templates/ # 타임리프 캐시 끄기(이 설정을 해야 꺼짐)
    enabled: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/qna_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      lazy-loading-enabled: true # 지연 로딩 활성화
    mapper-locations: classpath:/mapper/*.xml # 디렉토리에 MyBatis SQL Mapper 파일을 저장

  jpa:
    hibernate:
      ddl-auto: update # 옵션: none, validate, update, create, create-drop
    properties:
      hibernate:
        show_sql: true # 실행되는 SQL 쿼리 확인
        format_sql: true # 출력되는 SQL을 포맷팅
        use_sql_comments: true

  logging:
    level:
      root: INFO # 전체 애플리케이션에 대한 로그 레벨 설정
      org.springframework.web: DEBUG # Spring MVC 관련 요청 로그
      org.springframework.security: DEBUG
      # org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.mybatis: DEBUG
      org.apache.ibatis: DEBUG

  server:
    port: 8080

  aot:
    enabled: false